# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1dcc6f9d7510f0f258713c21de27d9de200cd707217731504f20e1accda37c127a3354ca7a5a4450ed8613cdcf09c789710002e6d214fca58100ea242a834d4

test:
  secret_key_base: 8c19587af9de2f3647b65625683d7f9ced2b23fb6a287902d1d7e40e454c3ddc97e54b2fa61720928687c1d506af9d850c2d4f22bb59470cc096190c572307d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
